### PR TITLE
Convert to Boogi template

### PR DESCRIPTION
**Pull request by ganicke**
File changes need to change over to the Boogi template.

### CODE REVIEW

**Comment by ganicke** [comment]
@pelikhan - I'm converting this repo to use the template I have in https://github.com/ganicke/makecode-apcsp. I use `yarn install` and this branch will build OK. The workflow build set in here (`build.yml`) is using `bahmutov/npm-install` instead. I wonder if it is missing some install step/s?

My local build for this branch:

```
C:\pxt-repos\makecode-csp>yarn build
yarn run v1.22.10
$ gatsby build --prefix-paths
warn Algolia App ID or Admin Key are not set!
success open and validate gatsby-configs - 0.169s
success load plugins - 2.201s
success onPreInit - 0.045s
success delete html and css files from previous builds - 0.020s
success initialize cache - 0.005s
success copy gatsby files - 0.124s
success onPreBootstrap - 0.025s
success createSchemaCustomization - 0.007s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.819s
success building schema - 0.456s
info Total nodes: 291, SitePage nodes: 23 (use --verbose for breakdown)
success createPages - 0.071s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.088s
success Cleaning up stale page-data - 0.018s
success update schema - 0.023s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.537s
success write out redirect data - 0.006s
success Build manifest and related icons - 0.145s
success onPostBootstrap - 0.150s
info bootstrap finished - 8.285s
success run static queries - 0.047s - 2/2 42.37/s
warn Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
success run page queries - 8.307s - 23/23 2.77/s
success write out requires - 0.015s
success Building production JavaScript and CSS bundles - 41.972s
success Rewriting compilation hashes - 0.003s
success Building static HTML for pages - 16.688s - 23/23 1.38/s
info Generated public/sw.js, which will precache 15 files, totaling 1038214 bytes.
The following pages will be precached:
/offline-plugin-app-shell-fallback/index.html
success onPostBuild - 0.149s
info Done building in 75.8314375 sec
```

**Comment by Jaqster** [comment]
Hey @abchatra - can you help Galen unblock?  Trying to get this curriculum published today (before the webinar goes live tomorrow morning)

**Comment by abchatra** [comment]
@pelikhan - I have no clue about this stack.

**Comment by ganicke** [comment]
We can make https://makecode.com/csp just point to https://ganicke.github.io/makecode-apcsp/ until we figure it out.

**Comment by pelikhan** [comment]
Can you do the work in this repo? It's easier to have a single source of truth.

**Comment by ganicke** [comment]
That's what I'm trying to do. I'm going to ice the temporary repo once I migrate this over. However, there's some simple dependency problem that the remote build has where my local build doesn't have using **this** repo on the **same** branch.

**Comment by ganicke** [comment]
Possible solution:

1. Nuke everything in this repo.
2. Bring over the stuff from the temp repo.
3. Create a new workflow with install, build, and deploy.

**Comment by ganicke** [comment]
Ha ha. It was a simple case-sensitivity problem with `./src/component` directory names.

**Pull request merged**
